// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsdFJFPlSU7w4kGENVbvVqmPkiToYmzTI',
    appId: '1:601195818143:web:012af6da899ba4c997c6aa',
    messagingSenderId: '601195818143',
    projectId: 'fidha-app-testing',
    authDomain: 'fidha-app-testing.firebaseapp.com',
    storageBucket: 'fidha-app-testing.firebasestorage.app',
    measurementId: 'G-P7G24Y5K8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD9xR7QqO80m0pRDlKdRgE-XEpQX2uZUQ',
    appId: '1:1071891136226:android:c70b0241a219ca4d84e8bb',
    messagingSenderId: '1071891136226',
    projectId: 'fidha-technologies',
    storageBucket: 'fidha-technologies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG8bdGlphi5Er5Zr8cIe-HKfQpsy9HgJQ',
    appId: '1:1071891136226:ios:883e940df60d2bcc84e8bb',
    messagingSenderId: '1071891136226',
    projectId: 'fidha-technologies',
    storageBucket: 'fidha-technologies.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfFkEccvLxQIEP7_DnLsQ-t9yTdUdYwQ',
    appId: '1:601195818143:ios:d8db4f11ef66375697c6aa',
    messagingSenderId: '601195818143',
    projectId: 'fidha-app-testing',
    storageBucket: 'fidha-app-testing.firebasestorage.app',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsdFJFPlSU7w4kGENVbvVqmPkiToYmzTI',
    appId: '1:601195818143:web:d98366e164b5110897c6aa',
    messagingSenderId: '601195818143',
    projectId: 'fidha-app-testing',
    authDomain: 'fidha-app-testing.firebaseapp.com',
    storageBucket: 'fidha-app-testing.firebasestorage.app',
    measurementId: 'G-THBGMHFBEY',
  );
}
